### ISSUE TITLE
PETA dataset is unavailable

### ISSUE THREAD

**Issue by jzsherlock4869** [speckean/upar_challenge#1]
The official download link for PETA dataset is not available, could you please provide other approaches to download this dataset? Thanks!

official link is as below (both cannot reach):
dropbox: https://www.dropbox.com/s/52ylx522hwbdxz6/PETA.zip?dl=0
ftp: http://mmlab.ie.cuhk.edu.hk/projects/projects/PETA_files/PETA.zip

**Comment by speckean** [comment]
Please use the download script provided in this repository: `python download_datasets.py`
I just tested it and the datasets download without any problem.

**Comment by speckean** [comment]
Unfortunately, we don't own the rights to the PETA data set and are therefore not allowed to share it via google drive. I suspect Dropbox is probably blocked for you. It is best to use a VPN to bypass the block.
